### ISSUE TITLE
[Request] Github Workflow building option

### ISSUE THREAD

**Issue by joeyoropesa-dev** [jooy2/flare-mobile#1]
It would be nice for users who cannot use their PC to be able to build this app and that can be done thanks to Github Workflow (Github Actions) feature.

That feature can do many things automatically including building apps from the source code without hardware requirements and tools by client to use it - everything is server-side.

**Comment by jooy2** [comment]
Hello,
As of the latest code, i'm no longer keeping it open source, so I'm closing the issue as this project is no longer maintained, sorry.
